service_one:
  section:
    heading: "Unsere Leistungen"
    description: "Warum Sie unsere Dienstleistungen <br> wählen sollten?"
  service1:
    icon: "assets/images/service/hausmeisterservice-martin-altenkirchen-haustechnik-kontrolle.png"
    alt: "service icon"
    heading: "Haustechnik-Kontrolle"
    description: "Regelmäßige Überprüfung Ihrer technischen Anlagen und Systeme."
    button:
      label: "Read More"
      link: "/service-details"
  service2:
    icon: "assets/images/service/hausmeisterservice-martin-altenkirchen-reparaturen.png"
    alt: "service icon"
    heading: "Kleine Reparaturen"
    description: "Schnelle und zuverlässige Durchführung von kleinen Reparaturen."
    button:
      label: "Read More"
      link: "/service-details"
  service3:
    icon: "assets/images/service/hausmeisterservice-martin-altenkirchen-betreuung-der-mieter.png"
    alt: "service icon"
    heading: "Betreuung der Mieter"
    description: "Persönliche Betreuung und Unterstützung Ihrer Mieter vor Ort."
    button:
      label: "Read More"
      link: "/service-details"
  service4:
    icon: "assets/images/service/hausmeisterservice-martin-altenkirchen-schluesselnotdienst.png"
    alt: "service icon"
    heading: "Schlüsselnotdienst"
    description: "24/7 Notdienst für schnelle Hilfe bei Schlüssel- und Schlossproblemen."
    button:
      label: "Read More"
      link: "/service-details"
  service5:
    icon: "assets/images/service/hausmeisterservice-martin-altenkirchen-muellentsorgung.png"
    alt: "service icon"
    heading: "Müllentsorgung"
    description: "Ordnungsgemäße und umweltfreundliche Entsorgung von Abfällen."
    button:
      label: "Read More"
      link: "/service-details"
  service6:
    icon: "assets/images/service/hausmeisterservice-martin-altenkirchen-renovierungsarbeiten.png"
    alt: "service icon"
    heading: "Renovierungsarbeiten"
    description: "Professionelle Renovierung und Modernisierung Ihrer Immobilie."
    button:
      label: "Read More"
      link: "/service-details"
  service7:
    heading: "Wir bieten umfassende Dienstleistungen rund um <span> Technik, Pflege und Reparaturen</span>"
    description: "Wir bieten darüber hinaus weitere Leistungen an. Senden Sie uns eine Anfrage, und wir prüfen, wie wir Ihnen helfen können." 
    button:
      label: "Termin vereinbaren"
      link: "/contact"

service_two:
  image: "assets/images/service/hausmeisterservice-martin-altenkirchen-leistungsmerkmale.jpg"
  subheading: "Services"
  heading: "Leistungsmerkmale für unsere Hausmeisterdienste"
  button:
    label: "Termin vereinbaren"
    link: "/contact"
  feature1:
    one: "Haustechnik-Wartung"
    two: "Kleininstandsetzungen"
    three: "Mieterbetreuung vor Ort"
    four: "Abfallmanagement"
  feature2:
    one: "24/7 Schlüsselnotdienst"
    two: "Garten- und Landschaftspflege"
    three: "Treppenhausreinigung"
    four: "Renovierungsservice"

service_three:
  section:
    heading: "Our Services"
    description: "Why will you choose our <br> services?"
  service1:
    icon: "assets/images/service/landscape.png"
    alt: "service icon"
    heading: "Landscape Design"
    description: "There are many variations of passages the majority have suffered alteration form."
    button:
      label: "Read More"
      url: "/service-details"
  service2:
    icon: "assets/images/service/growing.png"
    alt: "service icon"
    heading: "Plant Growing"
    description: "There are many variations of passages the majority have suffered alteration form."
    button:
      label: "Read More"
      url: "/service-details"
  service3:
    icon: "assets/images/service/harvest.png"
    alt: "service icon"
    heading: "Branch Cutting"
    description: "There are many variations of passages the majority have suffered alteration form."
    button:
      label: "Read More"
      url: "/service-details"
  service4:
    icon: "assets/images/service/flower.png"
    alt: "service icon"
    heading: "Flower Scaping"
    description: "There are many variations of passages the majority have suffered alteration form."
    button:
      label: "Read More"
      url: "/service-details"
  service5:
    icon: "assets/images/service/tree.png"
    alt: "service icon"
    heading: "Tree Planting"
    description: "There are many variations of passages the majority have suffered alteration form."
    button:
      label: "Read More"
      url: "/service-details"
  service6:
    icon: "assets/images/service/rubbish.png"
    alt: "service icon"
    heading: "Rubbish Removal"
    description: "There are many variations of passages the majority have suffered alteration form."
    button:
      label: "Read More"
      url: "/service-details"

service_four:
  section:
    heading: "Our Services"
    description: "Why will you choose our <br> services?"
  service1:
    icon: "assets/images/service/landscape.png"
    alt: "service icon"
    heading: "Landscape Design"
    description: "There are many variations of passages the majority have suffered alteration form."
    button:
      label: "Read More"
      url: "/service-details"
  service2:
    icon: "assets/images/service/growing.png"
    alt: "service icon"
    heading: "Plant Growing"
    description: "There are many variations of passages the majority have suffered alteration form."
    button:
      label: "Read More"
      url: "/service-details"
  service3:
    icon: "assets/images/service/harvest.png"
    alt: "service icon"
    heading: "Branch Cutting"
    description: "There are many variations of passages the majority have suffered alteration form."
    button:
      label: "Read More"
      url: "/service-details"